apiVersion: v1
kind: Pod
metadata:
  name: diffusion-pod
  namespace: 1-ashesh-tacs-lab
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "30Gi"
        cpu: "1"
      limits:
        nvidia.com/gpu: 1
        memory: "30Gi"
        cpu: "2"
    volumeMounts:
    - mountPath: /tmp
      name: app-data-volume
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  volumes:
    - name: app-data-volume
      persistentVolumeClaim:
        claimName: app-data-pvc
